Minor grammatical corrections and improvements
OWASP/DevGuide pull request #74
Opened 2021-01-13 11:54 UTC by PabloL007

This proposal includes minor grammatical corrections to `02-Design/01-Principles of Security Engineering.md`, as well as, the addition of an excerpt from "Basic Principles of Information Protection" that I found useful for better understanding the least common mechanism principle.

2021-02-02 08:57 UTC, PabloL007 commented
@kapilepatel I see you reviewed the last PR that was approved could you take a look a this one?

2021-02-04 08:40 UTC, PabloL007 commented
Maybe @bradchesney79 ?

2021-03-28 14:03 UTC, bradchesney79 commented on 02-Design/01-Principles of Security Engineering.md
> +Also known as the [compartmentalization principle][1], or separation of privilege, separation of duties is a security principle which states that the successful completion of a single task is depende
I like most of it, but completion of a single task doesn't agree with the plural of themselves.

2021-03-28 14:04 UTC, bradchesney79 requested changes
Line 21, themselves to itself. Plural direct object doesn't agree with singular subject. On the whole, nice edits otherwise. Thank you for your contribution.

2021-03-28 14:16 UTC, PabloL007 commented on 02-Design/01-Principles of Security Engineering.md
> +Also known as the [compartmentalization principle][1], or separation of privilege, separation of duties is a security principle which states that the successful completion of a single task is depende
True, changed back to itself and pushed

2021-03-28 14:19 UTC, PabloL007 commented
> Line 21, themselves to itself. Plural direct object doesn't agree with singular subject. On the whole, nice edits otherwise. Thank you for your contribution.

Happy to help, I changed it back to itself, let me know if there’s anything else

2021-04-29 09:47 UTC, bradchesney79 approved these changes

2021-04-29 09:47 UTC, merged